package baradir:manager;

world manager-app {
  import list-apps: func() -> list<string>;
  import get-domain: func() -> string;
  import install-app-from-binary: func(name: string, bytes: list<u8>) -> result<string>;
}
