[package]
name = "baradir"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["apps/manager", "apps/hello"]

[dependencies]
bytes = "1.12.1"
clap = { version = "4.6.6", features = ["derive"] }
http-body-util = "0.1.5"
hyper = "1.10.1"
rand = "0.10.2"
rusqlite = "0.40.2"
tokio = { version = "1.52.3", features = ["full"] }
tokio-macros = "2.7.0"
wasmtime = "47.0.2"
wasmtime-wasi = "47.0.2"
wasmtime-wasi-http = "47.0.2"
wiggle = "47.0.2"
